server:
  port: 8761

spring:
  application:
    name: discoveryservice

# ?????? ??? ????? ??(??? true)
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    # ???? ???? ?? ?????? ???? ?? ?? -> ?? ??????
    # ?? ???? ???? ???? ???? ?? ??
    # false? ???? ????? ???? ??? ?? ??
    # heart-beat? ???? ??? ?? ??? ?????.
    enable-self-preservation: false
    # ???????? heart-beat? ?? ????? ??(?? 60?)
    eviction-interval-timer-in-ms: 1000
